### ISSUE TITLE
incompatible with Internet Explorer and Edge?

### ISSUE THREAD

**Issue by XW913** [kyro46/assPaintQuestion#22]
Image error shows up in the feedback section, the overview of results and manual correction. Is it a known compatibility issue or it has something to do with the configuration of my computer?
![Fehler_ImageError](https://user-images.githubusercontent.com/62590428/77403596-b5ccf000-6db0-11ea-811b-07afcab515fd.jpg)

**Comment by kyro46** [comment]
Sorry for my inactivity. My employer changed 2019 and I can only occasionally check back. My best guess is, that the error is caused by code, ment to keep TCPDF-output alive. The img-tag-content includes a charater, TCPDF needs to pruduce a valid PDF, but browsers can't use. So there is a JS fallback-function to correct this, as soon as a browser uses this code and expectably has issues with this. Presumably, IE can't handle this.

Sorry for the inconvenience.

**Comment by kyro46** [comment]
Just to follow up - the workaround-code for TCPDF will be gone in the next version.
